// Auto-generated by scripts/generate-migrations.ts
// Não editar manualmente - executar 'pnpm migrations:generate' após adicionar novos arquivos .sql

export const migrations: { version: number; name: string }[] = [
  {
    "version": 1,
    "name": "initial"
  }
];

export const LATEST_VERSION = 1;
