// Auto-generated by scripts/generate-migrations.ts
// Não editar manualmente - executar 'pnpm migrations:generate' após adicionar novos arquivos .sql

export const migrations: { version: number; name: string }[] = [
  {
    "version": 1,
    "name": "initial"
  },
  {
    "version": 3,
    "name": "dates_to_text"
  },
  {
    "version": 4,
    "name": "stock_movements"
  },
  {
    "version": 5,
    "name": "entry_payment_type"
  }
];

export const LATEST_VERSION = 5;
