import * as fs from 'fs';
import * as path from 'path';
import Database from 'better-sqlite3';

const MIGRATIONS_DIR = path.join(__dirname, '../lib/database/migrations');
const OUTPUT_FILE = path.join(__dirname, '../lib/database/generated-migrations.ts');
const DB_PATH = path.join(__dirname, '../stock_sales.db');

function parseMigrationVersion(filename: string): { version: number; name: string } | null {
  const match = filename.match(/^(\d+)_([a-zA-Z0-9_]+)\.sql$/);
  if (!match) return null;
  return {
    version: parseInt(match[1], 10),
    name: match[2],
  };
}

function getCurrentVersion(db: Database.Database): { version: number; alreadyExists: boolean } {
  const tables = db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='db_version'").all();
  
  if (tables.length === 0) {
    db.exec(`
      CREATE TABLE IF NOT EXISTS db_version (
        version INTEGER PRIMARY KEY,
        appliedAt TEXT NOT NULL
      );
    `);
    return { version: 0, alreadyExists: false };
  }

  const result = db.prepare("SELECT COALESCE(MAX(version), 0) as version FROM db_version").get() as { version: number };
  return { version: result?.version || 0, alreadyExists: true };
}

function runMigrations(db: Database.Database, migrations: { version: number; name: string; sql: string }[]) {
  const { version: currentVersion } = getCurrentVersion(db);
  
  console.log(`\n[Database] Versão atual do banco: ${currentVersion}`);
  console.log(`[Database] Total de migrations disponíveis: ${migrations.length}\n`);

  for (const migration of migrations) {
    if (migration.version <= currentVersion) {
      console.log(`[Database] Migração v${migration.version}_${migration.name} já aplicada, pulando...`);
      continue;
    }

    console.log(`[Database] Aplicando migração v${migration.version}_${migration.name}...`);

    try {
      db.exec(migration.sql);

      console.log(`[Database] ✓ Migração v${migration.version}_${migration.name} aplicada com sucesso!\n`);
    } catch (error) {
      console.error(`[Database] ✗ Erro ao aplicar migração v${migration.version}:`, error);
      process.exit(1);
    }
  }

  console.log('[Database] Migrações concluídas!');
}

function generateMigrations() {
  console.log('========================================');
  console.log('  GERADOR DE MIGRATIONS');
  console.log('========================================\n');

  if (!fs.existsSync(MIGRATIONS_DIR)) {
    console.error(`Erro: Diretório de migrations não encontrado: ${MIGRATIONS_DIR}`);
    process.exit(1);
  }

  const files = fs.readdirSync(MIGRATIONS_DIR).filter(f => f.endsWith('.sql'));

  if (files.length === 0) {
    console.log('Nenhum arquivo de migration encontrado.');
    fs.writeFileSync(OUTPUT_FILE, '// Auto-generated - não editar manualmente\nexport const migrations: { version: number; name: string }[] = [];\n');
    console.log('Arquivo gerado vazio.');
    return;
  }

  const migrationsList: { version: number; name: string; sql: string }[] = [];

  for (const filename of files) {
    const parsed = parseMigrationVersion(filename);
    if (!parsed) {
      console.warn(`Ignorando arquivo com nome inválido: ${filename}`);
      continue;
    }

    const filepath = path.join(MIGRATIONS_DIR, filename);
    const sql = fs.readFileSync(filepath, 'utf-8');

    migrationsList.push({
      version: parsed.version,
      name: parsed.name,
      sql: sql.trim(),
    });

    console.log(`Encontrado: ${filename} (v${parsed.version}_${parsed.name})`);
  }

  migrationsList.sort((a, b) => a.version - b.version);

  const output = `// Auto-generated by scripts/generate-migrations.ts
// Não editar manualmente - executar 'pnpm migrations:generate' após adicionar novos arquivos .sql

export const migrations: { version: number; name: string }[] = ${JSON.stringify(
    migrationsList.map(m => ({ version: m.version, name: m.name })),
    null,
    2
)};
`;

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`\nGerado: ${OUTPUT_FILE}`);
  console.log(`Total de migrations: ${migrationsList.length}`);

  console.log('\n========================================');
  console.log('  EXECUTANDO MIGRATIONS NO BANCO');
  console.log('========================================\n');

  const db = new Database(DB_PATH);
  
  try {
    runMigrations(db, migrationsList);
  } finally {
    db.close();
  }
}

generateMigrations();