import * as fs from 'fs';
import * as path from 'path';
import initSqlJs, { Database as SqlJsDatabase } from 'sql.js';

const MIGRATIONS_DIR = path.join(__dirname, '../lib/database/migrations');
const OUTPUT_FILE = path.join(__dirname, '../lib/database/generated-migrations.ts');
const SCHEMA_OUTPUT_FILE = path.join(__dirname, '../lib/database/schema.ts');
const DB_PATH = path.join(__dirname, '../stock_sales.db');

function parseMigrationVersion(filename: string): { version: number; name: string } | null {
  const match = filename.match(/^(\d+)_([a-zA-Z0-9_]+)\.sql$/);
  if (!match) return null;
  return {
    version: parseInt(match[1], 10),
    name: match[2],
  };
}

async function getCurrentVersion(db: SqlJsDatabase): Promise<number> {
  const result = db.exec("SELECT name FROM sqlite_master WHERE type='table' AND name='db_version'");
  
  if (result.length === 0) {
    db.run(`
      CREATE TABLE IF NOT EXISTS db_version (
        version INTEGER PRIMARY KEY,
        appliedAt TEXT NOT NULL
      );
    `);
    return 0;
  }

  const versionResult = db.exec("SELECT COALESCE(MAX(version), 0) as version FROM db_version");
  return versionResult.length > 0 ? versionResult[0].values[0][0] as number : 0;
}

async function runMigrations(db: SqlJsDatabase, migrations: { version: number; name: string; sql: string }[]) {
  const currentVersion = await getCurrentVersion(db);
  
  console.log(`\n[Database] Versão atual do banco: ${currentVersion}`);
  console.log(`[Database] Total de migrations disponíveis: ${migrations.length}\n`);

  let hasChanges = false;

  for (const migration of migrations) {
    if (migration.version <= currentVersion) {
      console.log(`[Database] Migração v${migration.version}_${migration.name} já aplicada, pulando...`);
      continue;
    }

    console.log(`[Database] Aplicando migração v${migration.version}_${migration.name}...`);

    try {
      db.run(migration.sql);
      db.run('INSERT INTO db_version (version, appliedAt) VALUES (?, ?)', [migration.version, new Date().toISOString()]);
      hasChanges = true;

      console.log(`[Database] ✓ Migração v${migration.version}_${migration.name} aplicada com sucesso!\n`);
    } catch (error) {
      console.error(`[Database] ✗ Erro ao aplicar migração v${migration.version}:`, error);
      process.exit(1);
    }
  }

  if (hasChanges) {
    fs.writeFileSync(DB_PATH, db.export());
  }
  console.log('[Database] Migrações concluídas!');
}

async function generateMigrations() {
  console.log('========================================');
  console.log('  GERADOR DE MIGRATIONS');
  console.log('========================================\n');

  if (!fs.existsSync(MIGRATIONS_DIR)) {
    console.error(`Erro: Diretório de migrations não encontrado: ${MIGRATIONS_DIR}`);
    process.exit(1);
  }

  const files = fs.readdirSync(MIGRATIONS_DIR).filter(f => f.endsWith('.sql'));

  if (files.length === 0) {
    console.log('Nenhum arquivo de migration encontrado.');
    fs.writeFileSync(OUTPUT_FILE, '// Auto-generated - não editar manualmente\nexport const migrations: { version: number; name: string }[] = [];\nexport const LATEST_VERSION = 0;\n');
    fs.writeFileSync(SCHEMA_OUTPUT_FILE, '// Auto-generated - não editar manualmente\nexport interface Migration { version: number; name: string; sql: string; }\nexport const migrations: Migration[] = [];\nexport const LATEST_VERSION = 0;\n');
    console.log('Arquivos gerados vazios.');
    return;
  }

  const migrationsList: { version: number; name: string; sql: string }[] = [];

  for (const filename of files) {
    const parsed = parseMigrationVersion(filename);
    if (!parsed) {
      console.warn(`Ignorando arquivo com nome inválido: ${filename}`);
      continue;
    }

    const filepath = path.join(MIGRATIONS_DIR, filename);
    const sql = fs.readFileSync(filepath, 'utf-8');

    migrationsList.push({
      version: parsed.version,
      name: parsed.name,
      sql: sql.trim(),
    });

    console.log(`Encontrado: ${filename} (v${parsed.version}_${parsed.name})`);
  }

  migrationsList.sort((a, b) => a.version - b.version);

  const output = `// Auto-generated by scripts/generate-migrations.ts
// Não editar manualmente - executar 'pnpm migrations:generate' após adicionar novos arquivos .sql

export const migrations: { version: number; name: string }[] = ${JSON.stringify(
    migrationsList.map(m => ({ version: m.version, name: m.name })),
    null,
    2
)};

export const LATEST_VERSION = ${migrationsList.length > 0 ? migrationsList[migrationsList.length - 1].version : 0};
`;

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`\nGerado: ${OUTPUT_FILE}`);

  const schemaOutput = `// Auto-generated by scripts/generate-migrations.ts
// Não editar manualmente - executar 'pnpm migrations:generate' após adicionar novos arquivos .sql
// Este arquivo é bundlado no APK e usado para migrations em runtime

export interface Migration {
  version: number;
  name: string;
  sql: string;
}

export const migrations: Migration[] = ${JSON.stringify(migrationsList, null, 2)};

export const LATEST_VERSION = ${migrationsList.length > 0 ? migrationsList[migrationsList.length - 1].version : 0};
`;

  fs.writeFileSync(SCHEMA_OUTPUT_FILE, schemaOutput);
  console.log(`Gerado: ${SCHEMA_OUTPUT_FILE}`);

  console.log(`Total de migrations: ${migrationsList.length}`);

  console.log('\n========================================');
  console.log('  EXECUTANDO MIGRATIONS NO BANCO');
  console.log('========================================\n');

  const SQL = await initSqlJs();
  
  let db: SqlJsDatabase;
  if (fs.existsSync(DB_PATH)) {
    const fileBuffer = fs.readFileSync(DB_PATH);
    db = new SQL.Database(fileBuffer);
  } else {
    db = new SQL.Database();
  }
  
  await runMigrations(db, migrationsList);
}

generateMigrations();